name: Jest Coverage Comment
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npx jest --coverage --collectCoverageFrom='src/**/*.{ts,tsx}'

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-summary-path: ./coverage/coverage-summary.json
          junitxml-path: ./coverage/junit.xml
          title: "Jest Coverage Report"
          summary-title: "Coverage Summary"
          badge-title: "Coverage"
          junitxml-title: "Test Results"
          create-new-comment: true
