on:
  pull_request:
    types: [closed]

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Type
        id: determine_event
        run: |
          if [ "${{ github.event.pull_request.merged }}" == true ]; then
            echo "::set-output name=event_type::Pull Request Merged"
          fi

      - name: Send Telegram Notification
        if: steps.determine_event.outputs.event_type == 'Pull Request Merged'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 Pull Request Merged 🚀
            Author: ${{ github.actor }}
            Title: ${{ github.event.pull_request.title }}
            Link: ${{ github.event.pull_request.html_url }}
